services:
  document-indexer:
    image: document-indexer:latest
    build:
      context: ./document_indexer
      provenance: false
      sbom: false
    deploy:
      replicas: 0

  local-reindex:
    image: local-reindex:latest
    build:
      context: ./local-reindex
      additional_contexts:
        document-indexer: service:document-indexer
      provenance: false
      sbom: false
    env_file:
      - path: ./local-reindex/.env
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${LOCAL_DOCS_HOST}:${LOCAL_DOCS_CONTAINER}
    restart: unless-stopped

  local-cv:
    image: local-reindex:latest
    build:
      context: ./local-reindex
      additional_contexts:
        document-indexer: service:document-indexer
      provenance: false
      sbom: false
    env_file:
      - path: ./local-reindex/.env.cv
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${LOCAL_CV_HOST}:${LOCAL_CV_CONTAINER}
    restart: unless-stopped

  smb-reindex:
    image: smb-reindex:latest
    build:
      context: ./smb-reindex
      additional_contexts:
        document-indexer: service:document-indexer
      provenance: false
      sbom: false
    env_file:
      - path: ./smb-reindex/.env
        required: true
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${SMB_STAGING_HOST}:${SMB_STAGING_CONTAINER}
    restart: unless-stopped
    profiles:
      - smb
